### ISSUE TITLE
想弱弱的问一下__webpack_require__这个参数在哪定义的

### ISSUE THREAD

**Issue by LJJCherry** [ReedSun/analysis-bundle.js-of-Webpack#1]
<img width="724" alt="dingtalk20180311171154" src="https://user-images.githubusercontent.com/12826705/37251673-66e52ab2-254f-11e8-968f-8d8d5d38c8e7.png">

**Comment by ReedSun** [comment]
函数也是对象的一种呀，也可以有自己的属性

**Comment by LJJCherry** [comment]
> 函数也是对象的一种呀，也可以有自己的属性

是的。。。年轻的时候不懂啊阿哈哈哈
